database:
  driver: mysql
  dsn: "root:root@tcp(127.0.0.1:3306)/tiny_build_server?charset=utf8&parseTime=true"
tls:
  certfile:
  keyfile:
storagebox:
  username: username
  password: changeme
  host: host:port
